### ISSUE TITLE
Support middlewares

### ISSUE THREAD

**Issue by abahmed** [abahmed/gearbox#9]
**global middlewares** are applied on all incoming requests that already have a matching handler

These metrics should be considered
- Introduce  **Use** method to add user's middleware function
- Middleware functions are executed in the same order they were added (chained)
- Middleware can decide to stop flow or continue

**Comment by muhammednagy** [comment]
I can do this one.

**Comment by muhammednagy** [comment]
So the final draft of the design is as follows:
We are going to have handlers array inside the gearbox object which will contain all app-level handlers.
we are gonna have handlers in the context as well and index of the current handler
and finally handlers in the registered routes tree.
they are all arrays of functions where the main handler is the last one.
all the routing methods ( get, post, and etc ) will accept multiple handlers instead of one handler.
basically the application gets a request matches it and executes the first handler which if passed will execute C.Next() and if failed will just respond with an error.
we keep the index inside the context as well as the handlers array and each Next call increases the index.
Having the first middleware as the first element in the context and the main handler as the last one.
The tree node will be the same except for the handler part it would-be handlers.
During the execution Context will have the App-level handlers/middlewares at the beginning of the handlers array then the original routing handlers/middlewares then the actual handler that will have the business logic normally.
